# Runs on branches with a name like 'hotfix/v{TAG}.', tagging each commit with an incrementing release candidate
# like v{TAG}.rc-{n}


name: 'âš™ï¸ ðŸš¨ Build hotfix'
on:
  push:
    branches:
      - 'hotfix/v*'
jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Calculate tag names'
        id: tags
        run: |
          releaseBranch=$(git branch --show-current | grep hotfix/v*)
          branchTag=${releaseBranch#hotfix/}
          lastTag=$(git describe --match "$branchTag-hotfix.[0-9]*" --abbrev=0 HEAD) || lastTag=NONE
          if [[ $lastTag =~ $branchTag-hotfix\.([0-9]*) ]]; then
            current="$branchTag-hotfix.$((BASH_REMATCH[1]+1))"
          else
            current="$branchTag-hotfix.0"
          fi

          echo $current
          echo "::set-output name=previous::$lastTag"
          echo "::set-output name=current::$current"

      - uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: ${{ steps.tags.outputs.current }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fail if tag exists
        if: steps.checkTag.outputs.exists == 'true'
        run: |
          echo "Tag already exists"
          exit 1

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.tags.outputs.current }}
          tag_prefix: ""

      - name: Enhance changelog
        id: changelog
        env:
          CHANGELOG: ${{ steps.tag_version.outputs.changelog }}
          JIRA_PROJECT: TT
          JIRA_HOST: tickets.customer.com
        run: |
          newChangelog="$(echo "$CHANGELOG" |  sed "s/$JIRA_PROJECT-\([0-9]*\)/[$JIRA_PROJECT-\1](https:\/\/$JIRA_HOST\/browse\/$JIRA_PROJECT-\1)/g")"
          echo "$newChangelog" > release_changelog.md
          echo "::set-output name=enhanced::$newChangelog"

      - name: Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: ${{ steps.tags.outputs.current }}
          name: ${{ steps.tags.outputs.relTag }}
          body_path: release_changelog.md
          token: ${{ secrets.GITHUB_TOKEN }}
